name: REACT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    env:
        AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
        AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
        AZURE_APPSERVICEPLAN_NAME: ${{ vars.AZURE_APPSERVICEPLAN_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      id: checkout

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Build app
      run: |
        cd app
        npm run build
        cd build
        zip -r webapp.zip .

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Resources
      run: |
        az group create --name $AZURE_RESOURCE_GROUP --location westeurope --managed-by IAC
        az deployment group create --resource-group $AZURE_RESOURCE_GROUP --template-file infrastructure/main.bicep --parameters appName=$AZURE_WEBAPP_NAME appServicePlanName=$AZURE_APPSERVICEPLAN_NAME

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: app/build/*.zip

    - name: logout
      run: az logout
